// Products data
const products = [
  {
    id: 1,
    name: "Midnight Bloom",
    description:
      "A captivating floral scent with notes of jasmine and vanilla that evolves throughout the day. The top notes feature bergamot and pink pepper, while the heart reveals jasmine, rose, and ylang-ylang. The base notes of vanilla, sandalwood, and musk provide a warm, lasting finish.",
    price: 89.99,
    category: "women",
    images: [
      "https://placehold.co/400x400?text=Midnight+Bloom+1",
      "https://placehold.co/400x400?text=Midnight+Bloom+2",
      "https://placehold.co/400x400?text=Midnight+Bloom+3",
    ],
    sizes: ["30ml", "50ml", "100ml"],
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    details: {
      fragrance_family: "Floral Oriental",
      concentration: "Eau de Parfum",
      longevity: "8-10 hours",
      sillage: "Moderate to strong",
      season: "All seasons",
      release_year: 2023,
      perfumer: "Emma Laurent",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Linalool, Limonene, Butylphenyl Methylpropional, Citronellol, Coumarin, Geraniol, Hexyl Cinnamal, Benzyl Benzoate, Citral, Benzyl Alcohol, Farnesol, Eugenol, Isoeugenol, Cinnamal, Benzyl Cinnamate, CI 17200 (Red 33), CI 60730 (Ext. Violet 2), CI 19140 (Yellow 5).",
    reviews: [
      {
        id: 1,
        user: "Sarah J.",
        rating: 5,
        date: "2023-12-15",
        comment:
          "This has become my signature scent! I receive compliments every time I wear it. The jasmine and vanilla combination is divine.",
      },
      {
        id: 2,
        user: "Michael T.",
        rating: 4,
        date: "2023-11-28",
        comment:
          "Bought this for my wife and she loves it. Great longevity and the scent evolves beautifully throughout the day.",
      },
      {
        id: 3,
        user: "Emma R.",
        rating: 5,
        date: "2023-10-10",
        comment:
          "Absolutely stunning fragrance. Perfect for both day and evening wear. The bottle is also very elegant.",
      },
    ],
    featured: true,
  },
  {
    id: 2,
    name: "Ocean Breeze",
    description:
      "Fresh and invigorating with citrus and marine accords. The top notes feature bergamot and sea salt, while the heart reveals aquatic notes and lavender. The base notes of ambergris and cedar provide a clean, lasting finish.",
    price: 75.99,
    category: "men",
    images: [
      "https://placehold.co/400x400?text=Ocean+Breeze+1",
      "https://placehold.co/400x400?text=Ocean+Breeze+2",
      "https://placehold.co/400x400?text=Ocean+Breeze+3",
    ],
    sizes: ["50ml", "100ml", "150ml"],
    rating: 4.6,
    reviewCount: 98,
    stock: 22,
    details: {
      fragrance_family: "Aquatic Aromatic",
      concentration: "Eau de Toilette",
      longevity: "6-8 hours",
      sillage: "Moderate",
      season: "Spring/Summer",
      release_year: 2022,
      perfumer: "Jean Dubois",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Methoxycinnamate, Citral, Citronellol, Geraniol, CI 42090 (Blue 1), CI 60730 (Ext. Violet 2).",
    reviews: [
      {
        id: 1,
        user: "David M.",
        rating: 5,
        date: "2023-08-15",
        comment: "Perfect summer scent. Fresh and long-lasting without being overpowering.",
      },
      {
        id: 2,
        user: "Alex P.",
        rating: 4,
        date: "2023-07-22",
        comment: "Great everyday fragrance. The marine notes are very realistic.",
      },
    ],
    featured: true,
  },
  {
    id: 3,
    name: "Amber Woods",
    description:
      "Warm and sophisticated with amber, sandalwood, and musk. The top notes feature bergamot and black pepper, while the heart reveals cedarwood and patchouli. The base notes of amber, vanilla, and musk provide a rich, lasting finish.",
    price: 95.99,
    category: "unisex",
    images: [
      "https://placehold.co/400x400?text=Amber+Woods+1",
      "https://placehold.co/400x400?text=Amber+Woods+2",
      "https://placehold.co/400x400?text=Amber+Woods+3",
    ],
    sizes: ["30ml", "50ml", "100ml"],
    rating: 4.9,
    reviewCount: 76,
    stock: 18,
    details: {
      fragrance_family: "Woody Oriental",
      concentration: "Eau de Parfum",
      longevity: "10-12 hours",
      sillage: "Strong",
      season: "Fall/Winter",
      release_year: 2023,
      perfumer: "Sofia Chen",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Coumarin, Limonene, Linalool, Eugenol, Citronellol, Geraniol, Cinnamal, Benzyl Benzoate, Benzyl Alcohol, CI 15985 (Yellow 6), CI 17200 (Red 33).",
    reviews: [
      {
        id: 1,
        user: "Jordan K.",
        rating: 5,
        date: "2023-11-30",
        comment: "Incredible depth and complexity. Works beautifully on all genders.",
      },
      {
        id: 2,
        user: "Taylor R.",
        rating: 5,
        date: "2023-10-15",
        comment: "My new favorite fragrance. The amber and sandalwood combination is perfect.",
      },
    ],
    featured: true,
  },
  {
    id: 4,
    name: "Rose Elixir",
    description:
      "Elegant and timeless with Bulgarian rose and patchouli. The top notes feature bergamot and raspberry, while the heart reveals rose, peony, and lily of the valley. The base notes of patchouli, amber, and vanilla provide a sophisticated, lasting finish.",
    price: 110.99,
    category: "women",
    images: [
      "https://placehold.co/400x400?text=Rose+Elixir+1",
      "https://placehold.co/400x400?text=Rose+Elixir+2",
      "https://placehold.co/400x400?text=Rose+Elixir+3",
    ],
    sizes: ["30ml", "50ml", "100ml"],
    rating: 4.7,
    reviewCount: 112,
    stock: 9,
    details: {
      fragrance_family: "Floral Chypre",
      concentration: "Eau de Parfum",
      longevity: "8-10 hours",
      sillage: "Moderate to strong",
      season: "All seasons",
      release_year: 2022,
      perfumer: "Isabella Rossi",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Citronellol, Geraniol, Linalool, Limonene, Hydroxycitronellal, Alpha-Isomethyl Ionone, Benzyl Benzoate, Eugenol, Farnesol, Benzyl Alcohol, CI 17200 (Red 33), CI 15985 (Yellow 6).",
    reviews: [
      {
        id: 1,
        user: "Olivia S.",
        rating: 5,
        date: "2023-09-20",
        comment: "The most beautiful rose fragrance I've ever worn. Modern yet classic.",
      },
      {
        id: 2,
        user: "Sophia L.",
        rating: 4,
        date: "2023-08-05",
        comment: "Sophisticated and feminine. Perfect for special occasions.",
      },
    ],
    featured: true,
  },
  {
    id: 5,
    name: "Citrus Splash",
    description:
      "Energizing blend of lemon, bergamot, and grapefruit. The top notes feature zesty citrus, while the heart reveals green tea and jasmine. The base notes of vetiver and white musk provide a clean, lasting finish.",
    price: 65.99,
    category: "unisex",
    images: ["https://placehold.co/400x400?text=Citrus+Splash+1", "https://placehold.co/400x400?text=Citrus+Splash+2"],
    sizes: ["50ml", "100ml"],
    rating: 4.5,
    reviewCount: 87,
    stock: 25,
    details: {
      fragrance_family: "Citrus Aromatic",
      concentration: "Eau de Toilette",
      longevity: "4-6 hours",
      sillage: "Moderate",
      season: "Spring/Summer",
      release_year: 2023,
      perfumer: "Marco Bianchi",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Citral, Geraniol, Citronellol, Farnesol, CI 19140 (Yellow 5), CI 42090 (Blue 1).",
    reviews: [
      {
        id: 1,
        user: "Jamie L.",
        rating: 5,
        date: "2023-07-12",
        comment: "So refreshing! Perfect for hot summer days.",
      },
      {
        id: 2,
        user: "Casey P.",
        rating: 4,
        date: "2023-06-30",
        comment: "Clean and uplifting. Great for the office.",
      },
    ],
    featured: false,
  },
  {
    id: 6,
    name: "Leather & Oud",
    description:
      "Rich and intense with leather, oud, and spices. The top notes feature saffron and cardamom, while the heart reveals leather and rose. The base notes of oud, amber, and patchouli provide a deep, lasting finish.",
    price: 120.99,
    category: "men",
    images: ["https://placehold.co/400x400?text=Leather+Oud+1", "https://placehold.co/400x400?text=Leather+Oud+2"],
    sizes: ["50ml", "100ml"],
    rating: 4.9,
    reviewCount: 65,
    stock: 12,
    details: {
      fragrance_family: "Woody Oriental",
      concentration: "Eau de Parfum",
      longevity: "12+ hours",
      sillage: "Strong",
      season: "Fall/Winter",
      release_year: 2022,
      perfumer: "Ahmed Al-Jabri",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Coumarin, Limonene, Linalool, Eugenol, Cinnamal, Benzyl Benzoate, Benzyl Alcohol, Citronellol, Geraniol, CI 14700 (Red 4), CI 17200 (Red 33).",
    reviews: [
      {
        id: 1,
        user: "Robert K.",
        rating: 5,
        date: "2023-12-05",
        comment: "Powerful and masculine. The longevity is incredible.",
      },
      {
        id: 2,
        user: "James W.",
        rating: 5,
        date: "2023-11-18",
        comment: "Sophisticated and luxurious. Worth every penny.",
      },
    ],
    featured: false,
  },
  {
    id: 7,
    name: "Vanilla Dreams",
    description:
      "Sweet and comforting with vanilla, caramel, and musk. The top notes feature bergamot and almond, while the heart reveals vanilla and tonka bean. The base notes of caramel, sandalwood, and musk provide a warm, lasting finish.",
    price: 85.99,
    category: "women",
    images: [
      "https://placehold.co/400x400?text=Vanilla+Dreams+1",
      "https://placehold.co/400x400?text=Vanilla+Dreams+2",
    ],
    sizes: ["30ml", "50ml", "100ml"],
    rating: 4.7,
    reviewCount: 93,
    stock: 18,
    details: {
      fragrance_family: "Oriental Gourmand",
      concentration: "Eau de Parfum",
      longevity: "8-10 hours",
      sillage: "Moderate to strong",
      season: "Fall/Winter",
      release_year: 2023,
      perfumer: "Claire Dubois",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Coumarin, Limonene, Linalool, Benzyl Benzoate, Benzyl Alcohol, Citronellol, Geraniol, Eugenol, CI 15985 (Yellow 6), CI 42090 (Blue 1).",
    reviews: [
      {
        id: 1,
        user: "Natalie P.",
        rating: 5,
        date: "2023-10-25",
        comment: "Like a warm hug in a bottle. So cozy and delicious.",
      },
      {
        id: 2,
        user: "Hannah M.",
        rating: 4,
        date: "2023-09-14",
        comment: "Sweet but not cloying. Perfect for colder months.",
      },
    ],
    featured: false,
  },
  {
    id: 8,
    name: "Mountain Pine",
    description:
      "Fresh and aromatic with pine, cedar, and mint. The top notes feature mint and eucalyptus, while the heart reveals pine and fir balsam. The base notes of cedar, vetiver, and moss provide a crisp, lasting finish.",
    price: 79.99,
    category: "men",
    images: ["https://placehold.co/400x400?text=Mountain+Pine+1", "https://placehold.co/400x400?text=Mountain+Pine+2"],
    sizes: ["50ml", "100ml", "150ml"],
    rating: 4.6,
    reviewCount: 78,
    stock: 20,
    details: {
      fragrance_family: "Aromatic Fougère",
      concentration: "Eau de Toilette",
      longevity: "6-8 hours",
      sillage: "Moderate",
      season: "All seasons",
      release_year: 2022,
      perfumer: "Thomas Schmidt",
    },
    ingredients:
      "Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Eugenol, Citral, Citronellol, Geraniol, Coumarin, CI 42090 (Blue 1), CI 19140 (Yellow 5).",
    reviews: [
      {
        id: 1,
        user: "Daniel R.",
        rating: 5,
        date: "2023-08-30",
        comment: "Smells like a walk in the forest. Very refreshing and natural.",
      },
      {
        id: 2,
        user: "Chris B.",
        rating: 4,
        date: "2023-07-15",
        comment: "Great everyday scent. Clean and masculine without being overpowering.",
      },
    ],
    featured: false,
  },
]
